services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HADOOP_CONF_DFS_NAMENODE_RPC_ADDRESS=namenode:9000 
      - HADOOP_CONF_DFS_NAMENODE_NAME_DIR=/hadoop/dfs/name
      - HADOOP_CONF_DFS_DATANODE_DATA_DIR=/hadoop/dfs/data
      - HADOOP_CONF_DFS_REPLICATION=1
    ports:
      - "9870:9870"
      - "9000:9000"
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HADOOP_CONF_dfs_namenode_rpc_address=namenode:9000
      - HADOOP_CONF_DFS_REPLICATION=1
    ports:
      - "9864:9864"
    networks:
      - hadoop

  spark-master:
    image: docker.io/bitnami/spark:3.5
    container_name: spark-master
    depends_on:
      - namenode
      - datanode
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - HADOOP_CONF_DIR=/etc/hadoop
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - hadoop

  postgres:
    image: postgres:15
    container_name: hive-postgres
    environment:
      - POSTGRES_DB=hive_metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive -d hive_metastore"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hadoop

  hive-metastore-init:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore-init
    depends_on:
      postgres:
        condition: service_healthy
      namenode:
        condition: service_started
      datanode:
        condition: service_started
    environment:
      - SERVICE_PRECONDITION="postgres:5432 namenode:9000"
      - DB_TYPE=postgresql
      - DB_DRIVER=org.postgresql.Driver
      - DB_USER=hive
      - DB_PASS=hive
      - DB_URL=jdbc:postgresql://postgres:5432/hive_metastore
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    command: >
      bash -c "
      echo 'Waiting for postgres...'
      while ! nc -z postgres 5432; do 
        echo 'Postgres not ready, waiting...'
        sleep 2
      done
      echo 'Postgres is ready, initializing schema...'
      /opt/hive/bin/schematool -dbType postgres -initSchema -verbose"
    networks:
      - hadoop

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    depends_on:
      postgres:
        condition: service_healthy
      hive-metastore-init:
        condition: service_completed_successfully
    environment:
      - SERVICE_PRECONDITION="postgres:5432 namenode:9000"
      - DB_TYPE=postgresql
      - DB_DRIVER=org.postgresql.Driver
      - DB_USER=hive
      - DB_PASS=hive
      - DB_URL=jdbc:postgresql://postgres:5432/hive_metastore
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    command: /opt/hive/bin/hive --service metastore
    ports:
      - "9083:9083"
    networks:
      - hadoop

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    depends_on:
      - hive-metastore
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://postgres:5432/hive_metastore
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionUserName=hive
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionPassword=hive
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionDriverName=org.postgresql.Driver
    ports:
      - "10000:10000"
    networks:
      - hadoop

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hive_metastore:
  postgres_data: 

networks:
  hadoop:
    name: hadoop